### ISSUE TITLE
material-dev-tools not works as expected

### ISSUE THREAD

**Issue by liudonghua123** [mallowigi/material-dev-tools#14]
I installed the extension from https://chrome.google.com/webstore/detail/material-devtools-theme-c/jmefikbdhgocdjeejjnnepgnfkkbpgjo?hl=en-US, and the material dark theme and restart the chrome. Open some page, press Ctrl+Shift+I to open dev tools. But the dev tools seems the same as before.
I am using the latest Chrome v83.

Any ideas about this?

![image](https://user-images.githubusercontent.com/2276718/82986122-dd963980-a027-11ea-8e88-c9650a9da6ba.png)

![image](https://user-images.githubusercontent.com/2276718/82986241-16cea980-a028-11ea-8fdf-5795a6cba958.png)

![image](https://user-images.githubusercontent.com/2276718/82986187-00285280-a028-11ea-8edd-5cca5575a95d.png)

**Comment by randyFRS** [comment]
I realize this issue is a tad old, but I was having an issue, too. For @liudonghua123, I suggest restarting DevTools (and hopefully you already have).
For me, I was stuck on where to change the theme after setting a "parent theme" in the Preferences > Appearance section of DevTools. I suggest an edit/update to the installation/setup documentation on the Chrome Web Store. For one thing, the chrome://flags step is no longer necessary. Also, mention that this _is still an Extension_, and as such, one needs to go to chrome://extensions/, find the extension, click Details, then click Extension Options to find and set the actual theme. Or, link to the page, if possible: [chrome-extension://jmefikbdhgocdjeejjnnepgnfkkbpgjo/public/index.html](chrome-extension://jmefikbdhgocdjeejjnnepgnfkkbpgjo/public/index.html).

**Comment by liudonghua123** [comment]
Finally, I tried to change the dev theme from system to dark, then set one of the dark theme in `chrome-extension://jmefikbdhgocdjeejjnnepgnfkkbpgjo/public/index.html`. Then it worked.

So the dark or light theme settings should be match for both extension and dev tools.

![image](https://user-images.githubusercontent.com/2276718/90644756-b1293c80-e267-11ea-9eb6-c9d45e1f4e84.png)
